-- Growth OS LaunchHub native admin form operations
-- Raw public tokens are generated by the server and only SHA-256 hashes enter DB.

begin;

create or replace function public.launchhub_admin_create_form(
  p_client_id uuid,
  p_brand_id uuid,
  p_client_key text,
  p_brand_key text,
  p_form_key text,
  p_token_hash text,
  p_title text,
  p_allowed_domains text[],
  p_service_id uuid,
  p_package_id uuid,
  p_location_id uuid,
  p_conversion_mode text,
  p_success_redirect_base_url text,
  p_is_test_form boolean
)
returns table(form_id uuid)
language plpgsql
security invoker
set search_path = public
as $$
declare
  new_form_id uuid;
begin
  if p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'launchhub_admin_token_hash_invalid';
  end if;

  if coalesce(cardinality(p_allowed_domains), 0) = 0 then
    raise exception 'launchhub_admin_allowed_domains_required';
  end if;

  if not exists (
    select 1 from public.brands b
    where b.id = p_brand_id and b.client_id = p_client_id and b.status = 'active'
  ) then
    raise exception 'launchhub_admin_brand_scope_invalid';
  end if;

  if not exists (
    select 1 from public.launchhub_services s
    where s.id = p_service_id and s.client_id = p_client_id
      and s.brand_id = p_brand_id and s.status = 'active'
  ) then
    raise exception 'launchhub_admin_service_scope_invalid';
  end if;

  if not exists (
    select 1 from public.launchhub_packages p
    where p.id = p_package_id and p.client_id = p_client_id
      and p.brand_id = p_brand_id and p.service_id = p_service_id
      and p.status = 'active'
  ) then
    raise exception 'launchhub_admin_package_scope_invalid';
  end if;

  if not exists (
    select 1 from public.launchhub_locations l
    where l.id = p_location_id and l.client_id = p_client_id
      and l.brand_id = p_brand_id and l.status = 'active'
  ) then
    raise exception 'launchhub_admin_location_scope_invalid';
  end if;

  insert into public.lead_forms (
    client_id, brand_id, client_key, brand_key, form_key,
    public_form_token_hash, title, is_active, is_test_form, allowed_domains
  ) values (
    p_client_id, p_brand_id, p_client_key, p_brand_key, p_form_key,
    p_token_hash, p_title, true, p_is_test_form, p_allowed_domains
  ) returning id into new_form_id;

  insert into public.launchhub_form_configs (
    lead_form_id, client_id, brand_id, default_service_id,
    default_package_id, default_location_id, conversion_mode,
    success_redirect_base_url, metadata_json
  ) values (
    new_form_id, p_client_id, p_brand_id, p_service_id,
    p_package_id, p_location_id, p_conversion_mode,
    nullif(p_success_redirect_base_url, ''),
    jsonb_build_object('token_version', 1, 'token_rotated_at', now())
  );

  return query select new_form_id;
end;
$$;

create or replace function public.launchhub_admin_update_form(
  p_form_id uuid,
  p_title text,
  p_allowed_domains text[],
  p_is_active boolean,
  p_service_id uuid,
  p_package_id uuid,
  p_location_id uuid,
  p_conversion_mode text,
  p_success_redirect_base_url text
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  scoped_client_id uuid;
  scoped_brand_id uuid;
begin
  select f.client_id, f.brand_id
  into scoped_client_id, scoped_brand_id
  from public.lead_forms f
  join public.launchhub_form_configs c on c.lead_form_id = f.id
  where f.id = p_form_id;

  if scoped_client_id is null or scoped_brand_id is null then
    raise exception 'launchhub_admin_form_not_found';
  end if;

  if coalesce(cardinality(p_allowed_domains), 0) = 0 then
    raise exception 'launchhub_admin_allowed_domains_required';
  end if;

  if not exists (
    select 1 from public.launchhub_services s
    where s.id = p_service_id and s.client_id = scoped_client_id
      and s.brand_id = scoped_brand_id and s.status = 'active'
  ) then
    raise exception 'launchhub_admin_service_scope_invalid';
  end if;

  if not exists (
    select 1 from public.launchhub_packages p
    where p.id = p_package_id and p.client_id = scoped_client_id
      and p.brand_id = scoped_brand_id and p.service_id = p_service_id
      and p.status = 'active'
  ) then
    raise exception 'launchhub_admin_package_scope_invalid';
  end if;

  if not exists (
    select 1 from public.launchhub_locations l
    where l.id = p_location_id and l.client_id = scoped_client_id
      and l.brand_id = scoped_brand_id and l.status = 'active'
  ) then
    raise exception 'launchhub_admin_location_scope_invalid';
  end if;

  update public.lead_forms
  set title = p_title,
      allowed_domains = p_allowed_domains,
      is_active = p_is_active,
      updated_at = now()
  where id = p_form_id;

  update public.launchhub_form_configs
  set default_service_id = p_service_id,
      default_package_id = p_package_id,
      default_location_id = p_location_id,
      conversion_mode = p_conversion_mode,
      success_redirect_base_url = nullif(p_success_redirect_base_url, ''),
      updated_at = now()
  where lead_form_id = p_form_id;

  return true;
end;
$$;

create or replace function public.launchhub_admin_rotate_form_token(
  p_form_id uuid,
  p_token_hash text
)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
begin
  if p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'launchhub_admin_token_hash_invalid';
  end if;

  update public.lead_forms
  set public_form_token_hash = p_token_hash,
      updated_at = now()
  where id = p_form_id
    and exists (
      select 1 from public.launchhub_form_configs c where c.lead_form_id = p_form_id
    );

  if not found then
    raise exception 'launchhub_admin_form_not_found';
  end if;

  update public.launchhub_form_configs
  set metadata_json = coalesce(metadata_json, '{}'::jsonb)
      || jsonb_build_object(
        'token_version', coalesce((metadata_json->>'token_version')::int, 0) + 1,
        'token_rotated_at', now()
      ),
      updated_at = now()
  where lead_form_id = p_form_id;

  return true;
end;
$$;

create or replace function public.launchhub_admin_duplicate_form(
  p_source_form_id uuid,
  p_form_key text,
  p_token_hash text,
  p_title text
)
returns table(form_id uuid)
language plpgsql
security invoker
set search_path = public
as $$
declare
  source_form public.lead_forms%rowtype;
  source_config public.launchhub_form_configs%rowtype;
  new_form_id uuid;
begin
  if p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'launchhub_admin_token_hash_invalid';
  end if;

  select * into source_form
  from public.lead_forms
  where id = p_source_form_id;

  select * into source_config
  from public.launchhub_form_configs
  where lead_form_id = p_source_form_id;

  if source_form.id is null or source_config.lead_form_id is null then
    raise exception 'launchhub_admin_form_not_found';
  end if;

  insert into public.lead_forms (
    client_id, brand_id, client_key, brand_key, form_key,
    public_form_token_hash, title, is_active, is_test_form, allowed_domains
  ) values (
    source_form.client_id, source_form.brand_id, source_form.client_key,
    source_form.brand_key, p_form_key, p_token_hash, p_title,
    true, source_form.is_test_form, source_form.allowed_domains
  ) returning id into new_form_id;

  insert into public.launchhub_form_configs (
    lead_form_id, client_id, brand_id, default_service_id,
    default_package_id, default_location_id, conversion_mode,
    success_redirect_base_url, metadata_json
  ) values (
    new_form_id, source_config.client_id, source_config.brand_id,
    source_config.default_service_id, source_config.default_package_id,
    source_config.default_location_id, source_config.conversion_mode,
    source_config.success_redirect_base_url,
    jsonb_build_object('token_version', 1, 'token_rotated_at', now(), 'duplicated_from', p_source_form_id)
  );

  return query select new_form_id;
end;
$$;

revoke all on function public.launchhub_admin_create_form(
  uuid,uuid,text,text,text,text,text,text[],uuid,uuid,uuid,text,text,boolean
) from public, anon, authenticated;
revoke all on function public.launchhub_admin_update_form(
  uuid,text,text[],boolean,uuid,uuid,uuid,text,text
) from public, anon, authenticated;
revoke all on function public.launchhub_admin_rotate_form_token(uuid,text)
  from public, anon, authenticated;
revoke all on function public.launchhub_admin_duplicate_form(uuid,text,text,text)
  from public, anon, authenticated;

grant execute on function public.launchhub_admin_create_form(
  uuid,uuid,text,text,text,text,text,text[],uuid,uuid,uuid,text,text,boolean
) to service_role;
grant execute on function public.launchhub_admin_update_form(
  uuid,text,text[],boolean,uuid,uuid,uuid,text,text
) to service_role;
grant execute on function public.launchhub_admin_rotate_form_token(uuid,text)
  to service_role;
grant execute on function public.launchhub_admin_duplicate_form(uuid,text,text,text)
  to service_role;

commit;
